# Use the official NGINX image
FROM nginx:alpine

# Copy the NGINX configuration
COPY config/nginx-dev.conf /etc/nginx/nginx.conf

# Expose port 8080
EXPOSE 8080

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]